### ISSUE TITLE
Unable to test relay and publish events

### ISSUE THREAD

**Issue by 1440000bytes** [fiatjaf/relayer#110]
I have setup a nostr relay using expensive-relay with these commands:

```
torify /root/relay-project/cln/usr/local/bin/lightningd --bitcoin-rpcconnect=REDACTED.onion --bitcoin-rpcport=8332 --bitcoin-rpcuser=REDACTED --bitcoin-rpcpassword=REDACTED --bind-addr=127.0.0.1:12345
```
```
POSTGRESQL_DATABASE=postgres://postgres:REDACTED@localhost:5432/postgres LN_NODE_ID=REDACTED CLN_HOST=127.0.0.1:12345 TICKET_PRICE_SATS=10000 CLN_RUNE=REDACTED /usr/local/bin/expensive
```

I can see the webpage to get invoice:

![image](https://github.com/fiatjaf/relayer/assets/147166694/c03b2000-d923-4999-a3e8-244228e001bd)

How do I test the relay now and publish events? I could not see anything using nostcat:

```
$ nostcat ws://127.0.0.1:7447
^C
```

**Comment by fiatjaf** [comment]
use https://github.com/fiatjaf/nak
