### ISSUE TITLE
Cannot write 2 events from same pubkey at the same time

### ISSUE THREAD

**Issue by prolic** [fiatjaf/relayer#2]
ERROR:  duplicate key value violates unique constraint "pubkeytimeidx"
DETAIL:  Key (pubkey, created_at)=(, 10) already exists.

**Comment by fiatjaf** [comment]
Is this really a bug? Why do you want to write two events at the same time?

**Comment by prolic** [comment]
Set metadata plus set contacts upon registration. What does it prevent?
Since I can set any time anyway, it's a rather useless "protection". Right
now I just add a second manually to the second event.

**Comment by fiatjaf** [comment]
Yeah, you're right. I'll fix it.

**Comment by barkyq** [comment]
Just tested this. Seems to be fine to publish multiple events from same pubkey with same `created_at`. Moving to close.
