### ISSUE TITLE
limit filter field returns earliest events

### ISSUE THREAD

**Issue by barkyq** [fiatjaf/relayer#25]
The handler/storage code seems to return the earliest events (uses postgreSQL default ordering, when `events[:limit]` is returned):

https://github.com/fiatjaf/relayer/blob/38d0f481c138e6689e249394b7d75d2e74105662/handlers.go#L233-L235

Also perhaps can be optimized by using the limit in the SQL query? The limit filter field does not seem to be used in: https://github.com/fiatjaf/relayer/blob/38d0f481c138e6689e249394b7d75d2e74105662/storage/postgresql/query.go#L15

**Comment by barkyq** [comment]
Was also thinking of https://github.com/nostr-protocol/nips/issues/78, adding a `received_at` field in the relayer postgreSQL database. Might be breaking change though. Dunno if filter.Limit is supposed to use `created_at` field or some internal relay timestamp. Probably overkill though and best to just use `created_at`... just thinking out loud...

**Comment by fiatjaf** [comment]
Yes, that would be good indeed.

**Comment by barkyq** [comment]
OK I will check it out.

**Comment by barkyq** [comment]
solved by #29
