### ISSUE TITLE
Relay Clustering using CRDTs

### ISSUE THREAD

**Issue by TheRook** [fiatjaf/relayer#33]
Dapp Database clustering has recently become possible with CRDTs and partially trusted datasets.  A relay doesn't need to blindly pass messages - but rather nodes can work together to create a logical database. CRDTs are the same data type that power Riak's Bitcask database engine which scales up to hundreds of millions of users (like Riot's Matrix.org project for example).

https://github.com/berty/go-orbit-db

Why is this needed:
It allows nostr to be run as a federated dapp and hosted by a community.
https://www.youtube.com/watch?v=cC-tXnMyiBc

**Comment by fiatjaf** [comment]
Please build it.

**Comment by TheRook** [comment]
We are building something more important than nostr. We will be submitting
a new protocol that replaces the extremely primitive message passing
system.
