### ISSUE TITLE
Enable TLS

### ISSUE THREAD

**Issue by zinderic** [fiatjaf/relayer#34]
The Nostr clients I've tested with require the use of TLS. Is this supported? I don't see a way to set a certificate and start the relayer in TLS mode so if I implement a simple client using https://github.com/nbd-wtf/go-nostr I'm getting an error:

```
2023/02/10 09:43:12 error opening websocket to 'wss://localhost:7447': tls: first record does not look like a TLS handshake
```

I tried using other clients like the mobile app Damus but it won't connect likely due to the same problem.

**Comment by fiatjaf** [comment]
The standard way of doing TLS is by having a reverse proxy like nginx or Caddy in front of the actual app that is running on localhost, that's why I didn't bother to add TLS.

But if someone wants to contribute an optional native-TLS mode I'm open to that.

**Comment by zinderic** [comment]
Right, I was thinking about adding something like nginx reverse proxy with self-signed certificate to the docker-compose setup in the basic example. But this won't help me much because then this self-signed certificate won't be trusted by nostr clients and I'm back where I started.

I'm trying to get to a development environment for building nostr relay where I can actually test the relay with a client. How do you normally go about doing that?

I can of course have a server with domain pointing to its public IP and trusted certificate so I can develop there but that's definitely not ideal setup. I would like to have something locally on my laptop but most clients I know don't have insecure mode or something like `curl -k ...` to ignore that the certificate is not trusted.

**Comment by barkyq** [comment]
I often test without TLS.

Connect to `ws://localhost:8080` or whatever the port is.

Might be an issue with "Access-Control" if you are using a web client, but should not be a problem if you also run a web client locally.

I also don't use docker, I just use `go run main.go`. Don't know if that will make a difference vis-a-vis TLS/etc

**Comment by barkyq** [comment]
Nevermind after testing I don't think access control header is used for websockets. I am not sure what you have to do.

**Comment by zinderic** [comment]
Oh yes, definitely. I can connect to the websocket with something like `websocat`. But that's not automatically a `nostr` client. Maybe I'll have a look at the protocol again and create some basic payloads to test with.

**Comment by barkyq** [comment]
OK cool. Well, I think web-browsers are a bit finicky about cross-origin stuff. But I can connect to my localhost websocket if I run a local web client. Perhaps running a desktop client will allow you to skip SSL? Maybe something like `gossip` client by Mike Dilger. Think @fiatjaf is a fan. It is built using rust which is not so hard to get set-up IIRC.

**Comment by zinderic** [comment]
Yeah, I tried `gossip` but it won't allow me to add localhost or use non-standard port different than 443. So I just tried adding entry in my /etc/hosts:

```
127.0.0.1 relay
```

And then I did some docker magic to have nginx reverse proxy opening my local 443 port and routing to the relay app which connects to the Postgres DB it needs. Even with this complicated setup `gossip` was not able to connect due to the self-signed certificate I use. This is the error I saw in the shell:

```
ERROR wss://relay: ERROR: HTTP (reqwest) error: error sending request for url (https://relay/): error trying to connect: The certificate was not trusted.
```

I tried also writing a simple client in Go using `github.com/nbd-wtf/go-nostr` which ended up having the same problem because I see no way to use insecure web socket. Am I missing something here? There must be a simple way of developing relay applications without all that TLS complexity.

**Comment by fiatjaf** [comment]
Maybe use https://github.com/blakejakopovic/nostcat.

**Comment by zinderic** [comment]
Oh yeah.. this one works:

```
bash-3.2$ echo '["REQ", "CID", {"limit": 1}]' |
>   ./nostcat wss://relay.damus.io |
>   jq -c 'del(.[1])' |
>   ./nostcat ws://localhost
["OK","b3db14b4b7933c8ab2bd6d503575437c045b37f10559ffdce36aa895fee301e4",true,""]

bash-3.2$
```

Thanks, that should help me figure out what's wrong with my basic client. At least now I know it's not a problem with my relay code :)

Another note for posterity and whoever gets into similar trouble and comes here to read - for insecure we should use `ws://` and not `wss://`. Part of my troubles were due to my ignorance of how web sockets work.

**Comment by zinderic** [comment]
Just tested with the `Damus` mobile app and it works just fine with `ws://` instead of `wss://`. Thanks for bearing with me, I'm closing this.
