### ISSUE TITLE
Events middleware API

### ISSUE THREAD

**Issue by qustavo** [fiatjaf/relayer#36]
Considering that the `relayer` repo is a framework for building nostr relayers rather than a concrete implementation, I think that a user of the framework could benefit from the idea of having composable middlewares that can handle events on a pipeline fashion.

Imagine someone wants to enable the following verification/operations before notifying a client about a given event:
- Event Deletion (NIP09)
- PoW (NIP13) to pass through/reject events.
- Some other form of rate limit
- Update prometheus metrics (no NIP)

In this example event deletions aren't subject to be gated by `PoW`, but if `PoW` gate reject the events the chain breaks.

Every one of these actions described above could be implemented as a middleware using a signature similar to this:

```go
type EventHandler func(event *nostr.Event) error

type Middleware func(EventHandler) EventHandler

func EventDeletionMiddleware(next EventHandler) EventHandler {
    fn := func(event *Nostr) error {
        if deleteEvent() {
            doDeletion()

            // break the middleware chain execution
            return nil
        }

        // next will execute `PoW` verification
        return next(event)
    }

    return fn
```

`relayer` could provide stock middlewares that the community might benefit from importing (most likely those defined on NIP).

Does this sound like a reasonable/useful feature to introduce?

**Comment by fiatjaf** [comment]
At first I don't like this. These middleware things always confuse me, it's never obvious what is happening. I think it is better if people just write their custom method and manually shove in there all the things you mention above.

If in the future we start to see a lot of repeated code for these functions then it will make sense to turn them into middlewares that can be used as packages.

**Comment by qustavo** [comment]
I understand your point, and yes, I agree sometimes is hard to know what's going on.
My feeling is that as a framework, relayer should provide some way to do the tedious and repetitive work. Maybe middlewares is not the best, and just public functions like `func(event *Event) bool` should be enough.
