### ISSUE TITLE
v2: context cancelled before save completes

### ISSUE THREAD

**Issue by bndw** [fiatjaf/relayer#50]
The new V2 refactor passes the request-scoped context to the storage methods, however since the save operation is handled async in a separate go routine the request-scoped context is canceled before the storage layer completes. The result is events are not saved.

Here's a quick hack of passing a new context to `SaveEvent` that proves this is the case:

```diff
diff --git a/add-event.go b/add-event.go
index b686258..d875fdb 100644
--- a/add-event.go
+++ b/add-event.go
@@ -23,7 +23,7 @@ func AddEvent(ctx context.Context, relay Relay, evt nostr.Event) (accepted bool,
 			advancedSaver.BeforeSave(ctx, &evt)
 		}
 
-		if saveErr := store.SaveEvent(ctx, &evt); saveErr != nil {
+		if saveErr := store.SaveEvent(context.Background(), &evt); saveErr != nil {
 			switch saveErr {
 			case storage.ErrDupEvent:
 				return true, saveErr.Error()

```

I think there are a couple ways to handle this, but ultimately if handlers are to be async then we'll have to use non request-scoped contexts in the child routines.

**Comment by fiatjaf** [comment]
Nice catch, thank you. These contexts will drive me crazy any day now.
