### ISSUE TITLE
storage: support configurable limit

### ISSUE THREAD

**Issue by bndw** [fiatjaf/relayer#60]
The postgresql storage QueryEvents method currently has a [hard coded limit](https://github.com/fiatjaf/relayer/blob/master/storage/postgresql/query.go#L175-L176) of 100 events. 

I would like control over the maximum number of events my relay returns and propose adding a `QueryLimit` field to the exported `type PostgresBackend`. If set we use that as the upper bound, else we can default it to 100 as it is today.

Would you accept a pull request if I implement this?

Scanning the other storage implementations:
- elasticsearch has a limit of 1000
- postgresql has a limit of 100
- sqlite3 has a limit of 100

**Comment by fiatjaf** [comment]
Yes, that would be good.
