### ISSUE TITLE
gorilla panic: concurrent write to websocket 

### ISSUE THREAD

**Issue by bleebl33** [fiatjaf/relayer#7]
go version go1.19.2 linux/amd64
relayer v1.5.0 (`go install github.com/fiatjaf/relayer/basic@v1.5.0`)
I'm using postgresql.

```
Started Nostr relayer.
function \"tags_to_tagvalues\" already exists with same argument types"}
<nil> DBG listening addr=127.0.0.1:3003
concurrent write to websocket connection
goroutine 39 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0003ac0c0, 0x1, {0x0, 0x7f03569d55b8, 0x30})
        /home/meeseeks/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:610 +0x52b
github.com/gorilla/websocket.(*messageWriter).Close(0x0)
        /home/meeseeks/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:724 +0x45
github.com/gorilla/websocket.(*Conn).beginMessage(0xc0000f4840, 0xc0003ac120, 0x1)
        /home/meeseeks/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:473 +0x42
github.com/gorilla/websocket.(*Conn).NextWriter(0xc0000f4840, 0x1)
        /home/meeseeks/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:513 +0x45
github.com/gorilla/websocket.(*Conn).WriteJSON(0xc0003ac0f0, {0x6ba0e0, 0xc000446ff0})
        /home/meeseeks/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/json.go:24 +0x45
github.com/fiatjaf/relayer.handleWebsocket.func1.1.3({0xc0000f2c00, 0xd8, 0x200})
        /home/meeseeks/go/pkg/mod/github.com/fiatjaf/relayer@v1.1.3/handlers.go:147 +0x9c5
created by github.com/fiatjaf/relayer.handleWebsocket.func1.1
        /home/meeseeks/go/pkg/mod/github.com/fiatjaf/relayer@v1.1.3/handlers.go:72 +0x2b7
Main process exited, code=exited, status=2/INVALIDARGUMENT
Failed with result 'exit-code'.
```

Here's my nginx location directive:
```
location / { 
         proxy_pass http://127.0.0.1:3003;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection $connection_upgrade;
```

**Comment by i0x0ff** [comment]
Judging by the `function \"tags_to_tagvalues\" already exists with same argument types"}` error that I see in the logs I'm skeptical if you're running  v1.5.0 as that got fixed as well: https://github.com/fiatjaf/relayer/blob/d69479974c26d95dd4b626d9deea8e47653fa73f/storage/postgresql/init.go#L20

**Comment by i0x0ff** [comment]
If you've ran relayer via docker in the past, make sure you rebuild the container from scratch. If you just pull latest changes docker won't rebuild with those changes when you run `docker-compose up` for example.

To rebuild with latest code run `docker-compose build relay` and then run `docker-compose up` and I believe you shouldn't be having this problems anymore.

I'm assuming this is the problem because the `function \"tags_to_tagvalues\" already exists with same argument types"}` error was also already fixed but it seems to pop up for you in the logs.

**Comment by bleebl33** [comment]
I was building from source using `go install github.com/fiatjaf/relayer/basic@v1.5.0`

I've since switched to rust-rs-relay, so I don't mind if you close this issue as I won't be able to reproduce it for you anymore.
