### ISSUE TITLE
Add env port value to relay struct in main

### ISSUE THREAD

**Issue by epysqyli** [fiatjaf/relayer#70]
Minor consideration here, I was wondering why there's no relay struct field

```go
Port int `envconfig:"PORT"`
```

so as to then call `server.Start("0.0.0.0", r.Port)` in `func main()`, fetching the value from `docker-compose.yml` while trying things out locally.

Could this be added with a PR  (at least for basic)?

Thanks

**Comment by fiatjaf** [comment]
Yes, please! On basic.
