### ISSUE TITLE
Consider providing linux arm64 binaries

### ISSUE THREAD

**Issue by lukehoersten** [fiatjaf/relayer#74]
Please consider providing linux arm64 binaries for the example releases for use on raspberry pis.

**Comment by fiatjaf** [comment]
Relayer is just a framework, not a directly usable relay software. This codebase contains only some basic examples of what you can do with it.

Anyway, it's very easy to cross-compile Go yourself.

**Comment by fiatjaf** [comment]
No, I just selected the combinations I thought were most widely used.

You can cross-compile on your desktop and send the binary to the RPI.

**Comment by fiatjaf** [comment]
Next time I setup any automatic release with cross-compilation stuff I will include linux arm64.
