### ISSUE TITLE
master missing commits

### ISSUE THREAD

**Issue by bndw** [fiatjaf/relayer#87]
Still missing a handful of commits that were removed from master a week ago. Here's [one example](https://github.com/fiatjaf/relayer/pull/83).

What can we do to restore these commits?

And based on seeing https://github.com/fiatjaf/khatru, will relayer be maintained moving forward? It seems like khatru is a hard fork.

**Comment by fiatjaf** [comment]
I've included that one now.

**Comment by fiatjaf** [comment]
What do you think of khatru? Do you think it is better than relayer? I made because I couldn't bring myself to use relayer, it had too many flaws. If khatru is strictly superior then I don't see why we would want to keep messing with relayer.

**Comment by bndw** [comment]
I see you implemented LMDB which is something I am interested in. I will give it a deeper look.

**Comment by fiatjaf** [comment]
But then people will update to the v3 and everything will break for them and they will be mad.
