### ISSUE TITLE
"Not authorized: ..." error on web page

### ISSUE THREAD

**Issue by Fonta1n3** [fiatjaf/relayer#9]
I am running the expensive relay from master but unable to generate an invoice via the webpage.

Ive got CLN running, my env variables look correct, postgresql running without any issue, bitcoin-cli and lightning-cli are happy. When I go to `http://localhost:7447` and paste in a nostr pubkey to generate an invoice I get:
`Not authorized: method does not start with list AND method does not start with get AND method is not equal to summary`.  My `commando` plug in is not reporting any issues. Any clues on how I can troubleshoot this would be appreciated.

**Comment by fiatjaf** [comment]
You need a rune that is capable of calling both `invoice` and `listinvoices`.

**Comment by peterzion45** [comment]
Can someone out there tell me if this is a legit bitcoin Receipt?
https://mobile.twitter.com/fightwithmemes/status/1627051224041410561/photo/1
